// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VersionManagement.Repositories;

namespace VersionManagement.Migrations
{
    [DbContext(typeof(VersionContext))]
    [Migration("20180820105314_RenameToCreator")]
    partial class RenameToCreator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VersionManagement.Models.VersionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Creator")
                        .IsRequired();

                    b.Property<int>("Department");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("ReleaseNote");

                    b.Property<int>("Status");

                    b.Property<string>("VersionNumber")
                        .IsRequired();

                    b.Property<string>("VersionTitle")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
